import js from "@eslint/js";
import { defineConfig } from "eslint/config";
import tseslint from "typescript-eslint";

/** Files not yet clean of these rules. The list only shrinks: a file comes off it once it passes. */
const NOT_YET_CLEAN = [
  "server/adapters/decisions.ts",
  "server/adapters/paseo/host.ts",
  "server/catalog/launch.ts",
  "server/catalog/providers.ts",
  "server/catalog/seats.ts",
  "server/catalog/servers.ts",
  "server/core/config-file.ts",
  "server/core/gate.ts",
  "server/core/git.ts",
  "server/core/paths.ts",
  "server/desk/checks.ts",
  "server/desk/context.ts",
  "server/desk/notice.ts",
  "server/desk/project.ts",
  "server/desk/roster.ts",
  "server/desk/slots.ts",
  "server/desk/sweep.ts",
  "server/desk/tools/ask.ts",
  "server/desk/tools/incidents.ts",
  "server/runtime/control.ts",
  "server/runtime/seating.ts",
  "server/runtime/timeline.ts",
  "server/runtime/turns.ts",
  "server/runtime/watch-view.ts",
  "server/upkeep/migrate.ts",
  "test/catalog/content.test.ts",
  "test/catalog/kit.real.test.ts",
  "test/catalog/kit.test.ts",
  "test/catalog/launch.test.ts",
  "test/catalog/providers.test.ts",
  "test/catalog/seats.test.ts",
  "test/catalog/team.test.ts",
  "test/kit.ts",
  "test/mcp/team.test.ts",
  "test/runtime/code-backend.test.ts",
  "test/runtime/code-fakes.ts",
  "test/runtime/code-proxy.test.ts",
  "test/runtime/fake-timeline.ts",
  "test/runtime/half-open.test.ts",
  "test/runtime/kept-lead.test.ts",
  "test/runtime/keys.test.ts",
  "test/runtime/lines.test.ts",
  "test/runtime/listing.test.ts",
  "test/runtime/mail.test.ts",
  "test/runtime/opening.test.ts",
  "test/runtime/own-branch.test.ts",
  "test/runtime/panel.test.ts",
  "test/runtime/restart.test.ts",
  "test/runtime/rpc.test.ts",
  "test/runtime/seat-prompt.test.ts",
  "test/runtime/status.test.ts",
  "test/runtime/steer.test.ts",
  "test/runtime/team-socket.test.ts",
];

export default defineConfig(
  {
    ignores: [
      "node_modules",
      "client",
      "index.client.tsx",
      "mcp",
      "bin",
      "content",
      "harness",
      "catalog",
      "test/fixtures",
      ...NOT_YET_CLEAN,
    ],
  },
  js.configs.recommended,
  tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: { parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname } },
    rules: {
      "@typescript-eslint/no-floating-promises": [
        "error",
        {
          allowForKnownSafeCalls: [
            { from: "package", package: "node:test", name: ["test", "suite", "describe", "it"] },
          ],
        },
      ],
      "@typescript-eslint/no-unused-vars": [
        "error",
        { ignoreRestSiblings: true, argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/require-await": "off",
    },
  },
  { files: ["eslint.config.js"], extends: [tseslint.configs.disableTypeChecked] },
);
